[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = [
  'javascript',
  'jsx'
]

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = [
  'jsx'
]

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = [
  'toml'
]

[[plugins]]
repo = 'violetyk/neocomplete-php.vim'
on_ft = [
  'php'
]

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = [
  'scala'
]

[[plugins]]
repo = 'fatih/vim-go'
on_ft = [
  'go', 'golang'
]
