shell = "zsh"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
use = ["powerlevel10k.zsh-theme"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
use = ["src"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
